BlogApp/BlogApp/ViewModels/SingleViewModel.cs
namespace BlogApp.ViewModels
{
    public class SingleViewModel
    {
        public string Title { get; set; }
        public string Body { get; set; }
        public string PictureURL { get; set; }
        public string slugUri { get; set; }
        public DateTime PublishDate { get; set; }
    }
}

BlogApp/BlogApp/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;

namespace BlogApp.Controllers
{
    public class BlogController : Controller
    {
        public IActionResult Index() => View();
        [HttpGet("~/article/{slugUri}")]
        public IActionResult Single(string slugUri) => View();
        [HttpGet("~/tag/{tagslug}")]
        public IActionResult GetByTag(string tagslug)
        {
            return View();
        }
        [HttpGet("~/category/{categoryName}")]
        public IActionResult GetByCategory(string categoryName)
        {
            return View();
        }
    }
}

BlogApp/BlogApp/ViewComponents/BlogListViewComponent.cs
using BlogApp.Models;
using BlogApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BlogApp.ViewComponents
{
    public class BlogListViewComponent : ViewComponent
    {
        private readonly BlogDbContext context;

        public BlogListViewComponent(BlogDbContext context)
        {
            this.context = context;
        }
        public async Task<IViewComponentResult> InvokeAsync(string categoryName = null)
        {


            var model = new List<BlogListViewModel>();
            if (categoryName == null)
            {
                model = await (from q in context.Articles.Include(c => c.Category)
                               where q.Status == true
                               select new BlogListViewModel
                               {
                                   Author = q.AuthorName,
                                   BlogBody = q.Body,
                                   PictureURL = q.PictureURL,
                                   PublishedDate = q.PublishDate,
                                   SlugUri = q.SlugUri,
                                   Title = q.Title,

                               }).Take(5).ToListAsync();
            }


            return View(model);
        }
    }
}

BlogApp/BlogApp/ViewComponents/TagCloudViewComponent.cs
using BlogApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BlogApp.ViewComponents
{
    public class TagCloudViewComponent : ViewComponent
    {
        private readonly BlogDbContext context;
        public TagCloudViewComponent(BlogDbContext context)
        {
            this.context = context;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Tag> tags = await (from q in context.Tags
                                    select q).ToListAsync();


            return View(tags);
        }
    }
}

BlogApp/BlogApp/Views/Blog/Index.cshtml
@model MainPageViewModel
@section HeaderSection{
    <title>Blog index page</title>
}

<div class="container-fluid pb-4 pt-4 paddding">
    <div class="container paddding">
        <div class="row mx-0">
             @await Component.InvokeAsync("BlogList")
            <div class="col-md-3 animate-box" data-animate-effect="fadeInRight">
                @await Component.InvokeAsync("TagCloud")
                @await Component.InvokeAsync("MostPopular")
            </div>
        </div>
       
    </div>
</div>
@await Component.InvokeAsync("TrimbleCarouselBlog",new {categoryName="Teknoloji"})

BlogApp/BlogApp/Views/Blog/Single.cshtml
@model List<SingleViewModel>
@section HeaderSection{
    <title>Blog single page</title>
}
@{
    Layout = "_Layout";
    ViewData["body-class"] = "single";
}
@foreach (SingleViewModel m in Model){
<div id="fh5co-title-box" style="background-image: url(@Url.Content(m.PictureURL); background-position: 50% 90.5px;" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="page-title">
        <img src="@Url.Content(m.PictureURL)" alt="@m.Title">
        <span>@m.PublishDate.ToShortDateString()</span>
        <h2>@m.Title</h2>
    </div>
</div>
<div id="fh5co-single-content" class="container-fluid pb-4 pt-4 paddding">
    <div class="container paddding">
        <div class="row mx-0">
            <div class="col-md-8 animate-box" data-animate-effect="fadeInLeft">
               @m.Body
            </div>
            
            <div class="col-md-3 animate-box" data-animate-effect="fadeInRight">
                <div class="col-md-3 animate-box" data-animate-effect="fadeInRight">
                @await Component.InvokeAsync("TagCloud")
                @await Component.InvokeAsync("MostPopular")
            </div>
            </div>
        </div>
    </div>
    </div>
    break;
}
@await Component.InvokeAsync("TrimbleCarouselBlog",new {categoryName="Teknoloji"})